---
- name: set hostname based on inventory_hostname
  hostname:
    name: '{{ hostname }}'
  when: set_hostname == true

- name: add hostname to hosts
  lineinfile:
    dest: /etc/hosts
    insertafter: '^{{ip}} {{hostname}}'
    line: "{{ip}} {{hostname}}"
